Repository TheCreators/Bario, pull requests merged in 2022-08, with the labels that each got.

#9 Created player (closes #7)
  Assets/Input System.meta
  Assets/Input System/Bario.inputactions
  Assets/Input System/Bario.inputactions.meta
  Assets/Prefabs.meta
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Scripts.meta
  Assets/Scripts/Layers.cs
  Assets/Scripts/Layers.cs.meta
  Assets/Scripts/Player.cs
  Assets/Scripts/Player.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/TagManager.asset
Labels: enhancement

#11 Fixed input system
  Assets/Scripts/Player.cs
  ProjectSettings/ProjectSettings.asset
  UserSettings/Layouts/default-2021.dwlt
Labels: bug

#13 Added follow camera (closes #12)
  Assets/Prefabs/Follow Camera.prefab
  Assets/Prefabs/Follow Camera.prefab.meta
  Assets/Scenes/SampleScene.unity
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/SceneTemplateSettings.json
Labels: enhancement

#20 Locked Z axis rotation
  Assets/Prefabs/Player.prefab
Labels: enhancement

#26 Removed legs object and added raycast check
  Assets/Prefabs/Player.prefab
  Assets/Scripts/JumpPermission.cs
  Assets/Scripts/JumpPermission.cs.meta
  Assets/Scripts/Player.cs
  ProjectSettings/Physics2DSettings.asset
Labels: bug

#32 Added Roslynator package
  .editorconfig
  App.config
  Assets/Scripts/Arms.cs
  Assets/Scripts/Arms.cs.meta
  Assets/Scripts/JumpPermission.cs
  Assets/Scripts/Layers.cs
  Assets/Scripts/Layers.cs.meta
  Packages/Roslynator.Analyzers.4.1.1/.signature.p7s
  Packages/Roslynator.Analyzers.4.1.1/Roslynator.Analyzers.4.1.1.nupkg
  Packages/Roslynator.Analyzers.4.1.1/analyzers/dotnet/cs/Roslynator.CSharp.Analyzers.CodeFixes.dll
  Packages/Roslynator.Analyzers.4.1.1/analyzers/dotnet/cs/Roslynator.CSharp.Analyzers.dll
  Packages/Roslynator.Analyzers.4.1.1/analyzers/dotnet/cs/Roslynator_Analyzers_Roslynator.CSharp.Workspaces.dll
  Packages/Roslynator.Analyzers.4.1.1/analyzers/dotnet/cs/Roslynator_Analyzers_Roslynator.CSharp.dll
  Packages/Roslynator.Analyzers.4.1.1/analyzers/dotnet/cs/Roslynator_Analyzers_Roslynator.Common.dll
  Packages/Roslynator.Analyzers.4.1.1/analyzers/dotnet/cs/Roslynator_Analyzers_Roslynator.Core.dll
  Packages/Roslynator.Analyzers.4.1.1/analyzers/dotnet/cs/Roslynator_Analyzers_Roslynator.Workspaces.Common.dll
  Packages/Roslynator.Analyzers.4.1.1/analyzers/dotnet/cs/Roslynator_Analyzers_Roslynator.Workspaces.Core.dll
  Packages/Roslynator.Analyzers.4.1.1/docs/README.md
  Packages/Roslynator.Analyzers.4.1.1/icon.png
  Packages/Roslynator.Analyzers.4.1.1/tools/install.ps1
  Packages/Roslynator.Analyzers.4.1.1/tools/uninstall.ps1
  packages.config
Labels: feature
